### PR TITLE
subscription feature fixes

### PR DESCRIPTION
**Pull request by tejaskh3**
Date: 22 oct, 2024

Developer Name: @tejaskh3 

---

## Issue Ticket Number:-

- [link](https://github.com/Real-Dev-Squad/website-backend/issues/2123)

## Description:
- this PR I have made changes asked by @ankushdharkar 
1. First is the remove subscription link from the navbar.
2. Make the input box text black(different from placeholder)
3. match phone number regex from the backend.

Is Under Feature Flag

- [x] Yes
- [ ] No

Database changes

- [x] Yes
- [] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [x] Yes
- [ ] No

### Add relevant Screenshot below ( e.g test coverage etc. )
image

https://github.com/user-attachments/assets/00fbcb99-2836-4924-a2db-d0b104205f77

### Note: 

**Tests for this feature are in this PR: #945**

### CODE REVIEW

**Review by yesyash — DISMISSED** [review]

**Comment by yesyash** [comment]
### NOTE for approver: Please make sure the ticket for tests is added to the PR description before merging.

**Comment by tejaskh3** [comment]
> ### NOTE for approver: Please make sure the ticket for tests is added to the PR description before merging.

This is the stacked PR for test cases: https://github.com/Real-Dev-Squad/website-www/pull/945, we can merge stacked PR after this one.

**Review by vinit717 — DISMISSED** [review]

**Comment by vinit717** [comment]
Still, I didn't see any error when the user provide wrong information

**Comment by tejaskh3** [comment]
> Still, I didn't see any error when the user provide wrong information

I added that message in the placeholder, but I got your point just like tiny site the input box should become red

**Comment by tejaskh3** [comment]
> > Still, I didn't see any error when the user provide wrong information
> 
> I added that message in the placeholder, but I got your point just like tiny site the text should become red

**Review by Achintya-Chatterjee — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]

**Review by lakshayman — APPROVED** [review]
LGTM

**Review by MehulKChaudhari — APPROVED** [review]

**Pull request merged**
