### PR TITLE
Fixed : now can login with github directly

### PR DESCRIPTION
**Pull request by prankurnov15**
### Issue #301 

Changed the redirect URL.

### CODE REVIEW

**Review by prakashchoudhary07 — CHANGES_REQUESTED** [review]
Since any packages are not being added, there is no point in updating package-lock.json
Please remove this.

**Comment by prakashchoudhary07** [comment]
There is a button present for sign-in already which takes to signin button
https://github.com/Real-Dev-Squad/website-www/blob/ba3331d43a7da99495e64db9769142b66c397165/index.html#L92-L112

I think the code which updates sign-in button link to a fake GitHub page to disable

And that is happening here 
https://github.com/Real-Dev-Squad/website-www/blob/e73fbee0a16b059a5e8fd83a2851af6a930a94ec/js/index.js#L70-L74

What do you think?

**Comment by prankurnov15** [comment]
I will remove the package.json

**Comment by prankurnov15** [comment]
Yes you are right the button is responsible for redirecting the user to fake page , I have updated this to direct login with GitHub by updating the url inside the function.

**Review by prakashchoudhary07 — CHANGES_REQUESTED** [review]
You have deleted the package-lock.json, It should have been reverted to the previous version before updating it in this PR

**Pull request closed without merging**
