### PR TITLE
FIX: Sign In Button showing up even if the user Logged In

### LINKED ISSUE #535: Fix login button showing up for logged-in users
### Description:
`Sign in with Github` button showing up in the Navbar while refreshing/navigating among the Pages, when user is already Loggedin.

https://github.com/Real-Dev-Squad/todo-action-items/assets/69259490/1979d11d-f858-4a10-91b5-ed57a2b36443

### PR DESCRIPTION
**Pull request by kotesh-arya**
### Issue
 Closes #535 

### What is the change?

- Added a **.hidden** class to the `Sign in` & `Sign in with Github` buttons, which initially hides them.
- After the SELF-API call being made, based on it's success/fail the button will be shown acccordingly
- In the error case of the API-call I have targeted the two buttons from the DOM and removed the **.hidden** class on them.
- During the API call I have added Shimmer effect to avoid a Layout shift after the User Name, profile shows up.

### Is Development Tested?

- [x] Yes
- [ ] No

### Before / After Change Screenshots

Before :

https://github.com/Real-Dev-Squad/todo-action-items/assets/69259490/1979d11d-f858-4a10-91b5-ed57a2b36443

After :

https://github.com/Real-Dev-Squad/website-www/assets/69259490/15fc0c9e-b397-4b8c-bd9c-2a1458ab8a0e

### CODE REVIEW

**Comment by apurvkhare** [comment]
There is a visible layout shift when the button is hidden. I would propose two approaches to handle this
1. skeleton loading instead of hiding the button (preferred)
2. use `visibility: hidden`

**Comment by Abhay5855** [comment]
Looks Good to me @kotesh-arya, Resolve the comments suggested by @apurvkhare rest looks good.

**Review by Pratiyushkumar — APPROVED** [review]
LGTM

**Comment by kotesh-arya** [comment]
> There is a visible layout shift when the button is hidden. I would propose two approaches to handle this
> 
> 1. skeleton loading instead of hiding the button (preferred)
> 2. use `visibility: hidden`

Thanks for the great suggestion @apurvkhare  🙌🏻 
I have implemented the Shimmer effect to avoid the Layout shift 👍🏻

**Review by apurvkhare — APPROVED** [review]

**Review by bksh05 — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]

**Review by rohan09-raj — APPROVED** [review]

**Pull request merged**
