### PR TITLE
Dev to Main Sync

### PR DESCRIPTION
**Pull request by ajoykumardas12**

### CODE REVIEW

**Comment by AdityaRaj2097** [comment]
> _ No description provided. _
### Issue

Properly Disable Join Link #688


Provide a small description in points of what did you change :   We aren't currently accepting new join applications. The link to join RDS is currently disabled by using pointer-events: none, which can be easily overridden from browser devtools and then click on the link. The joining page link is also available in devtools inspect html, which can also be clicked to go to join form. so for solving this we will replace the value of href.

<h1>WHAT IS THE CHANGE :</h1>  removing the value of href from join button give below for dissable join button 




##### Example :

- Done this
- Made these changes

### Is Development Tested? NO

- [ ] Yes
- [x] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

After change image :+1: 







<h3>Test Stats:</h3> 
<p> Beforre</p>










<p> After</p>

**Comment by AdityaRaj2097** [comment]
> Developer name -@AdityaRaj2097
> 
> PR Number(s):- [join dissable button ](https://github.com/Real-Dev-Squad/website-www/pull/705)
> 
> Backend changes No
> 
> Frontend Changes Yes
> 
> Is Under Feature Flag Yes
> 
> Database changes No
> 
> Breaking changes No
> 
> Deployment notes NA
> 
> Tested in staging Yes

@ajoykumardas12 kindly check and please let me know if any changes further required

**Review by samyakshah3008 — APPROVED** [review]

**Review by aneenajohn — COMMENTED** [review]
LGTM

**Review by aneenajohn — APPROVED** [review]

**Comment by AdityaRaj2097** [comment]
> LGTM
I couldn't get LGTM ?@

> LGTM

I couldn't get it @aneenajohn

**Comment by aneenajohn** [comment]
> > LGTM
> > I couldn't get LGTM ?@
> 
> > LGTM
> 
> I couldn't get it @aneenajohn

I'm sorry for any confusion. LGTM means 'Looks Good To Me.'

**Comment by AdityaRaj2097** [comment]
> Merge

@aneenajohn thanks a lot for review pr

**Pull request merged**
