### PR TITLE
setup for testing

### PR DESCRIPTION
**Pull request by vaishalimaheshwari2000**
setup for testing

### CODE REVIEW

**Comment by sahsisunny** [comment]
Please add the run test command in the GitHub workflow file.
https://github.com/Real-Dev-Squad/website-www/actions/runs/5410277464/workflow?pr=509

**Comment by vaishalimaheshwari2000** [comment]
You meant .gitignore file, isn't it ?

**Comment by sahsisunny** [comment]
> You meant percy.yml file, aren't it ? In which I have to write all test command which is using for setup the jest ?

https://github.com/Real-Dev-Squad/website-www/blob/develop/.github/workflows/percy.yml

**Comment by satyam73** [comment]
Closing this since we don't need this now because this is for old vanilla site and we've migrated to Ember JS which already have test set up.

**Pull request closed without merging**
