### PR TITLE
fix: navpills alignment to center

### LINKED ISSUE #718: [UI]: Navbar pills not aligned
## Description: 

- Nav-pills on the left are aligned to top. I see the right part's pill is aligned to center and making it inconsistent across the navbar. To make consistent UI, let's have all the pills aligned to center. 

## Screenshot which displays the bug: 

image

## Fixed bug screenshot: 

image

### PR DESCRIPTION
**Pull request by samyakshah3008**
### Issue

Closes #718 

### What is the change?

- Navpills are now aligned to center. Initially the left section alignment was not consistent with the right section of Navbar. Hence this PR aims to fix it.

### Is Development Tested?

- [X] Yes
- [ ] No

#### Before/After Change Screenshots:

Before :

image

After :

image

### CODE REVIEW

**Comment by shubhamjaintech** [comment]
Looks good to me! @samyakshah3008

**Review by ardourApeX — APPROVED** [review]
LGTM

**Comment by samyakshah3008** [comment]
Thank you @shubhamjaintech @ardourApeX for reviews!

**Review by satyam73 — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by iamitprakash — CHANGES_REQUESTED** [review]
need to fix failing test case first

**Comment by satyam73** [comment]
Closing this since we've migrated our site to Ember and this PR was opened for Vanilla site

**Pull request closed without merging**
