### PR TITLE
  Fix the content margin/padding #176 

### PR DESCRIPTION
**Pull request by Yogeshp0012**
Attaching the images for reference
fifth-what
fifth-why
first-what
first-why
fourth-what
fourth-why
second-what
second-why
third-what
third-why

### CODE REVIEW

**Review by rohan09-raj — COMMENTED** [review]
Looks good to me, great work 🥳🥳🎉. We need one more approval. Then we can merge this.

**Review by akshay1502 — APPROVED** [review]

**Review by harshith-venkatesh — APPROVED** [review]
Based on the visual screenshots, everything looks good to me

**Comment by rohan09-raj** [comment]
> Based on the visual screenshots, everything looks good to me

Thanks, @harshith-venkatesh

**Comment by harshith-venkatesh** [comment]
Good work @Yogeshp0012

**Pull request merged**
