### PR TITLE
Website-www Sync-up Changes

### PR DESCRIPTION
**Pull request by harshith-venkatesh**
Updating website-www to the latest changes.

### CODE REVIEW

**Review by rohan09-raj — APPROVED** [review]
Approved from my side, everything is working fine on develop and code also looks good to me.

**Comment by shubham-y** [comment]
There are issues in [Art creator feature](https://github.com/Real-Dev-Squad/website-www/pull/179/commits/932344f7f86ad6fc2bbb14c717d58a6b6cfc756c)

- The mobile view does not seem to be implemented
image

- There is an Uncaught TypeError in `artFeature.js` file at [this line](https://github.com/Real-Dev-Squad/website-www/blob/e7f1785e6ed993cc0878f97e8b2f197219458996/js/artFeature.js#L17)

**Comment by rohan09-raj** [comment]
> There are issues in [Art creator feature](https://github.com/Real-Dev-Squad/website-www/pull/179/commits/932344f7f86ad6fc2bbb14c717d58a6b6cfc756c)
> 
> * The mobile view does not seem to be implemented
> 
> image
> 
> * There is an Uncaught TypeError in `artFeature.js` file at [this line](https://github.com/Real-Dev-Squad/website-www/blob/e7f1785e6ed993cc0878f97e8b2f197219458996/js/artFeature.js#L17)

Is the feature not working in mobile view or you are talking about responsiveness ??

**Comment by shubham-y** [comment]
> > There are issues in [Art creator feature](https://github.com/Real-Dev-Squad/website-www/pull/179/commits/932344f7f86ad6fc2bbb14c717d58a6b6cfc756c)
> > 
> > * The mobile view does not seem to be implemented
> > 
> > image
> > 
> > * There is an Uncaught TypeError in `artFeature.js` file at [this line](https://github.com/Real-Dev-Squad/website-www/blob/e7f1785e6ed993cc0878f97e8b2f197219458996/js/artFeature.js#L17)
> 
> Is the feature not working in mobile view or you are talking about responsiveness ??

I am talking about responsiveness but in this case it is also not working in both the views due to error in code

**Review by shubham-y — APPROVED** [review]

**Review by rohan09-raj — APPROVED** [review]

**Pull request merged**
