### PR TITLE
Redirect the new user to welcome page

### PR DESCRIPTION
**Pull request by Amandixit10**
### Issue
[https://github.com/Real-Dev-Squad/website-www/issues/645](https://github.com/Real-Dev-Squad/website-www/issues/645)

### What is the change?

Changed the goto.js file which is responsible to redirect the new user to the signup form.

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [x] Yes
- [ ] No

https://github.com/Real-Dev-Squad/website-www/assets/55151241/5b42f3df-50b3-4cf6-a175-ec11e66cc849

### CODE REVIEW

**Review by Achintya-Chatterjee — COMMENTED** [review]
Do we need tests here

**Comment by shubhamjaintech** [comment]
@Amandixit10 
Current commit msg is 'changes'
Can we try it making it more meaningful? 
image

Thanks man,

**Comment by Amandixit10** [comment]
> Do we need to add test stats here?

image

**Comment by Amandixit10** [comment]
> @Amandixit10 Current commit msg is 'changes' Can we try it making it more meaningful? image
> 
> Thanks man,

Thanks for pointing this out, will remember this.

**Comment by Amandixit10** [comment]
https://github.com/Real-Dev-Squad/website-www/assets/55151241/5b42f3df-50b3-4cf6-a175-ec11e66cc849

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by gauravsinhaweb — CHANGES_REQUESTED** [review]
could you add the test case result, to make sure your changes are not affecting other features
update: I can see test stats on comment, would be nice if you put it in description

**Review by gauravsinhaweb — APPROVED** [review]

**Pull request merged**
