### PR TITLE
[Ember-Migration] Created Scroll To Top Button

### LINKED ISSUE #334: [Ember-Migration] Scroll to Top
## Feature
- Create a button which on clicking, scrolls the page to top

## Design Reference
image

### PR DESCRIPTION
**Pull request by rohan09-raj**
## Resolves Issue
Closes #334 

## What is the change?
- Created scroll to top button

## Is Development Tested?
- [x] Yes

## Before / After Change Screenshots
**Web View**
image

**Mobile View**
image

## Note for the Reviewer
- CI is failing due to package-lock.json being not found as we are using yarn.lock here. Therefore, need to update the Workflows or create a new workflow. Issue for the same - #327 
- Tests will be written in a PR. It is being tracked in the issue #281

### CODE REVIEW

**Review by heyrandhir — APPROVED** [review]
LGTM 🙂👍🏻

**Comment by rohan09-raj** [comment]
> LGTM slightly_smiling_face👍🏻

Thanks @heyrandhir  😄

**Review by harshith-venkatesh — COMMENTED** [review]
Good work on adding this Rohan as this is a great UX improvement task. This will help users a lot.

**Comment by rohan09-raj** [comment]
> Good work on adding this Rohan as this is a great UX improvement task. This will help users a lot.

Thank you so much @harshith-venkatesh

**Pull request merged**
