### PR TITLE
Updated api endpoint from /users/self to /users?profile=true

### PR DESCRIPTION
**Pull request by Hariom01010**
Date: 07 Dec 2024

Developer Name: Hariom Vashista

---

## Issue Ticket Number:-

Real-Dev-Squad/todo-action-items#255 repo#2

## Description:

Add description of the PR here
This PR aims to remove the deprecated API endpoint /users/self and update it with /users?profile=true
Is Under Feature Flag

- [ ] Yes
- [X] No

Database changes

- [ ] Yes
- [X] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [X] No

Is Development Tested?

- [Y] Yes
- [ ] No

Tested in staging?

- [Y] Yes
- [ ] No

### CODE REVIEW

**Review by prakashchoudhary07 — APPROVED** [review]

**Comment by prakashchoudhary07** [comment]
@Hariom01010 Please check, Tests are failing

**Review by prakashchoudhary07 — CHANGES_REQUESTED** [review]
Tests are faling?

**Comment by Hariom01010** [comment]
> Tests are faling?
I will look into it sir. I have checked the console.logs and found the failing test. I will see what's causing it and fix it and update you asap.

**Comment by Hariom01010** [comment]
Hello Prakash sir, I tried to reproduce the failing tests as follows:
1. Cloned the repo again.
2. Made the changes.
3. Run npm lint:fix
4. Run ember test

Now all tests are passing for some reason. So i am not able to reproduce it. So i have created a new branch and will be closing this PR and create a new PR from that branch and the test result is OK there. Will attach the screenshot too sir.

**Pull request closed without merging**
